--[[
  Generated by Vortex Exporter v2.0.0 — Full Figma Support
  Source: 
  Panel: sem_título
  Date: 2026-06-14T23:32:07.277Z
  
  Features: Shapes, Gradients, Glow/Neon, Auto-Layout,
  Premium Animations (Spring, Bounce, Elastic), 
  Dropdowns, Checkboxes, Radios, Switches,
  Sliders, Progress Bars, Tabs, Tooltips,
  Rich Text, Custom Fonts, Design Tokens
  
  Do NOT edit manually. Edit the Figma file and re-export.
]]--

-- Screen dimensions
local sx, sy = guiGetScreenSize()

-- Animation tick
local tickCount = getTickCount()

--============================================================================
-- Panel State Variables
--============================================================================

local isOpen = true
local activeInput = nil

-- Window dragging
local isDragging = false
local dragOffsetX = 0
local dragOffsetY = 0
local winX, winY = 0, 0

-- Theme Configuration
local theme = {}
theme.primary = tocolor(0, 170, 255, 255)
theme.primaryHover = tocolor(0, 136, 204, 255)
theme.primaryLight = tocolor(224, 238, 255, 255)
theme.secondary = tocolor(108, 117, 125, 255)
theme.success = tocolor(40, 167, 69, 255)
theme.danger = tocolor(220, 53, 69, 255)
theme.warning = tocolor(255, 193, 7, 255)
theme.text = tocolor(255, 255, 255, 255)
theme.textSecondary = tocolor(173, 181, 189, 255)
theme.background = tocolor(17, 24, 39, 255)
theme.surface = tocolor(30, 39, 58, 255)
theme.border = tocolor(60, 70, 90, 255)

-- Check if mouse is within a rectangle
function isMouseInPosition(x, y, width, height)
    if not isCursorShowing() then return false end
    local cx, cy = getCursorPosition()
    local sx, sy = guiGetScreenSize()
    local cursorX = cx * sx
    local cursorY = cy * sy
    return (cursorX >= x and cursorX <= x + width
        and cursorY >= y and cursorY <= y + height)
end

-- Check if mouse is within a circle
function isMouseInCircle(cx, cy, radius)
    if not isCursorShowing() then return false end
    local mx, my = getCursorPosition()
    local sx, sy = guiGetScreenSize()
    local cursorX = mx * sx
    local cursorY = my * sy
    local dx = cursorX - cx
    local dy = cursorY - cy
    return (dx * dx + dy * dy) <= (radius * radius)
end

-- Get lerp value for animations
function lerp(a, b, t)
    return a + (b - a) * t
end

-- Clamp value
function clamp(val, min, max)
    return math.max(min, math.min(max, val))
end

-- Hover scale animation for buttons
function startHoverAnim(componentId)
    local anim = animations[componentId]
    if anim and anim.type == "hoverScale" then
        anim.startTime = getTickCount()
        anim.finished = false
        anim.value = 0
        anim.direction = 1
    end
end

function stopHoverAnim(componentId)
    local anim = animations[componentId]
    if anim and anim.type == "hoverScale" then
        anim.startTime = getTickCount()
        anim.finished = false
        anim.value = 1
        anim.direction = -1
    end
end

--============================================================================
-- sem_título — DX Render
--============================================================================

-- Main render handler
addEventHandler("onClientRender", root, function()
    if not isOpen then return end

    sx, sy = guiGetScreenSize()

    -- sem_título Window (399x497)
    local winX = (sx - 399) / 2
    local winY = (sy - 497) / 2

    -- Window background
    if theme.background then
        dxDrawRectangle(0, 0, sx, sy, theme.background)
    end

    dxDrawRectangle(winX, winY, 399, 497, theme.surface, true)

    -- Window title
    dxDrawText("Window", winX + 15, winY + 10, winX + 399 - 15, winY + 35, theme.text, 1.0, "default-bold", "left", "top", false, false, true)

end)

-- Resource event handlers
addEventHandler("onClientResourceStart", resourceRoot, function()
    outputChatBox("[sem_título] Panel loaded successfully!", 0, 170, 255)
end)

addEventHandler("onClientResourceStop", resourceRoot, function()
    -- Cleanup
    isOpen = false
end)

-- Toggle panel visibility with a command
addCommandHandler("sem_título", function()
    isOpen = not isOpen
    showCursor(isOpen, true)
    guiSetInputEnabled(isOpen)

    if isOpen then
        outputChatBox("[sem_título] Panel opened", 0, 170, 255)
    else
        activeInput = nil
        outputChatBox("[sem_título] Panel closed", 255, 100, 100)
    end
end)
