--[[
  Generated by Vortex Exporter v2.0.0 — Full Figma Support
  Source: 
  Panel: sem_título
  Date: 2026-06-15T03:33:01.503Z
  
  Features: Shapes, Gradients, Glow/Neon, Auto-Layout,
  Premium Animations (Spring, Bounce, Elastic), 
  Dropdowns, Checkboxes, Radios, Switches,
  Sliders, Progress Bars, Tabs, Tooltips,
  Rich Text, Custom Fonts, Design Tokens
  
  Do NOT edit manually. Edit the Figma file and re-export.
]]--

-- Screen dimensions
local sx, sy = guiGetScreenSize()

-- Animation tick
local tickCount = getTickCount()

--============================================================================
-- Panel State Variables
--============================================================================

local isOpen = true
local activeInput = nil

-- Window dragging
local isDragging = false
local dragOffsetX = 0
local dragOffsetY = 0
local winX, winY = 0, 0

-- Theme Configuration
local theme = {}
theme.primary = tocolor(0, 170, 255, 255)
theme.primaryHover = tocolor(0, 136, 204, 255)
theme.primaryLight = tocolor(224, 238, 255, 255)
theme.secondary = tocolor(108, 117, 125, 255)
theme.success = tocolor(40, 167, 69, 255)
theme.danger = tocolor(220, 53, 69, 255)
theme.warning = tocolor(255, 193, 7, 255)
theme.text = tocolor(255, 255, 255, 255)
theme.textSecondary = tocolor(173, 181, 189, 255)
theme.background = tocolor(17, 24, 39, 255)
theme.surface = tocolor(30, 39, 58, 255)
theme.border = tocolor(60, 70, 90, 255)

-- Check if mouse is within a rectangle
function isMouseInPosition(x, y, width, height)
    if not isCursorShowing() then return false end
    local cx, cy = getCursorPosition()
    local sx, sy = guiGetScreenSize()
    local cursorX = cx * sx
    local cursorY = cy * sy
    return (cursorX >= x and cursorX <= x + width
        and cursorY >= y and cursorY <= y + height)
end

-- Check if mouse is within a circle
function isMouseInCircle(cx, cy, radius)
    if not isCursorShowing() then return false end
    local mx, my = getCursorPosition()
    local sx, sy = guiGetScreenSize()
    local cursorX = mx * sx
    local cursorY = my * sy
    local dx = cursorX - cx
    local dy = cursorY - cy
    return (dx * dx + dy * dy) <= (radius * radius)
end

-- Get lerp value for animations
function lerp(a, b, t)
    return a + (b - a) * t
end

-- Clamp value
function clamp(val, min, max)
    return math.max(min, math.min(max, val))
end

-- Input state: Enter text...
local input_51_12_value = ""

-- Input focus on click
addEventHandler("onClientClick", root, function(button, state)
    if not isOpen or button ~= "left" or state ~= "down" then return end

    if isMouseInPosition(winX + 84, winY + 43, 94, 78) then
        activeInput = "51:12"
        return
    end

    -- Click outside clears focus
    activeInput = nil
end)

-- Character input handler
addEventHandler("onClientCharacter", root, function(char)
    if not isOpen then return end

    if activeInput == "51:12" then
        if string.len(input_51_12_value) < 64 then
            input_51_12_value = input_51_12_value .. char
        end
        return
    end

end)

-- Backspace handler for inputs
addEventHandler("onClientKey", root, function(button, press)
    if not isOpen or not press then return end

    if activeInput == "51:12" then
        if button == "backspace" then
            input_51_12_value = string.sub(input_51_12_value, 1, -2)
        end
        return
    end

end)

-- Hover scale animation for buttons
function startHoverAnim(componentId)
    local anim = animations[componentId]
    if anim and anim.type == "hoverScale" then
        anim.startTime = getTickCount()
        anim.finished = false
        anim.value = 0
        anim.direction = 1
    end
end

function stopHoverAnim(componentId)
    local anim = animations[componentId]
    if anim and anim.type == "hoverScale" then
        anim.startTime = getTickCount()
        anim.finished = false
        anim.value = 1
        anim.direction = -1
    end
end

--============================================================================
-- sem_título — DX Render
--============================================================================

-- Main render handler
addEventHandler("onClientRender", root, function()
    if not isOpen then return end

    sx, sy = guiGetScreenSize()

    -- sem_título Window (261x327)
    local winX = 733
    local winY = 361

    -- Background overlay
    dxDrawRectangle(0, 0, sx, sy, tocolor(29, 0, 116, 255), true)

    dxDrawRectangle(winX, winY, 261, 327, tocolor(66, 40, 40, 255), true)
    -- Corner radius: 49px (simulated with circles)
    dxDrawCircle(winX + 49, winY + 49, 49, 180, 270, theme.background, 16)
    dxDrawCircle(winX + 261 - 49, winY + 49, 49, 270, 360, theme.background, 16)
    dxDrawCircle(winX + 49, winY + 327 - 49, 49, 90, 180, theme.background, 16)
    dxDrawCircle(winX + 261 - 49, winY + 327 - 49, 49, 0, 90, theme.background, 16)

    -- Window title
    dxDrawText("Window", winX + 15, winY + 10, winX + 261 - 15, winY + 35, theme.text, 1.0, "default-bold", "left", "top", false, false, true)

    -- Input: Enter text...
    local inp_51_12X = winX + 84
    local inp_51_12Y = winY + 43
    local inp_51_12W = 94
    local inp_51_12H = 78
    local inp_51_12Focused = (activeInput == "51:12")
    local inp_51_12Border = inp_51_12Focused and theme.primary or theme.border
    dxDrawRectangle(inp_51_12X, inp_51_12Y, inp_51_12W, inp_51_12H, theme.surfaceAlt, true)
    dxDrawRectangle(inp_51_12X, inp_51_12Y, inp_51_12W, 2, inp_51_12Border, true)
    if inp_51_12_value == "" or inp_51_12_value == nil then
        dxDrawText("Enter text...", inp_51_12X + 10, inp_51_12Y, inp_51_12X + inp_51_12W - 10, inp_51_12Y + inp_51_12H, theme.textMuted, 1.0, "default", "left", "center")
    else
        dxDrawText(inp_51_12_value, inp_51_12X + 10, inp_51_12Y, inp_51_12X + inp_51_12W - 10, inp_51_12Y + inp_51_12H, theme.text, 1.0, "default", "left", "center")
    end
    if inp_51_12Focused and math.floor(getTickCount() / 500) % 2 == 0 then
        dxDrawRectangle((inp_51_12X + 10 + dxGetTextWidth(inp_51_12_value == "" and "" or inp_51_12_value, 1.0, "default")), inp_51_12Y + 5, 2, inp_51_12H - 10, theme.text)
    end

    -- Button: Button
    local btn_51_13X = winX + 90
    local btn_51_13Y = winY + 185
    local btn_51_13W = 82
    local btn_51_13H = 88
    local btn_51_13Hover = isMouseInPosition(btn_51_13X, btn_51_13Y, btn_51_13W, btn_51_13H)
    local btn_51_13Color = btn_51_13Hover and theme.primaryHover or theme.primary
    dxDrawRectangle(btn_51_13X, btn_51_13Y, btn_51_13W, btn_51_13H, btn_51_13Color, true)
    -- Corner radius: 33px (simulated with circles)
    dxDrawCircle(btn_51_13X + 33, btn_51_13Y + 33, 33, 180, 270, theme.background, 16)
    dxDrawCircle(btn_51_13X + btn_51_13W - 33, btn_51_13Y + 33, 33, 270, 360, theme.background, 16)
    dxDrawCircle(btn_51_13X + 33, btn_51_13Y + btn_51_13H - 33, 33, 90, 180, theme.background, 16)
    dxDrawCircle(btn_51_13X + btn_51_13W - 33, btn_51_13Y + btn_51_13H - 33, 33, 0, 90, theme.background, 16)
    dxDrawText("Button", btn_51_13X, btn_51_13Y, btn_51_13X + btn_51_13W, btn_51_13Y + btn_51_13H, theme.text, 1.0, "default-bold", "center", "center", false, false, true)

end)

-- Button click handling
addEventHandler("onClientClick", root, function(button, state, absoluteX, absoluteY)
    if not isOpen then return end
    if button ~= "left" or state ~= "down" then return end

    -- Button: Button
    if isMouseInPosition(winX + 90, winY + 185, 82, 88) then
        outputChatBox("Button clicked: Button")
        return
    end

end)

-- Resource event handlers
addEventHandler("onClientResourceStart", resourceRoot, function()
    outputChatBox("[sem_título] Panel loaded successfully!", 0, 170, 255)
end)

addEventHandler("onClientResourceStop", resourceRoot, function()
    -- Cleanup
    isOpen = false
end)

-- Toggle panel visibility with a command
addCommandHandler("sem_título", function()
    isOpen = not isOpen
    showCursor(isOpen, true)
    guiSetInputEnabled(isOpen)

    if isOpen then
        outputChatBox("[sem_título] Panel opened", 0, 170, 255)
    else
        activeInput = nil
        outputChatBox("[sem_título] Panel closed", 255, 100, 100)
    end
end)
